### ISSUE TITLE
Hack dem globus!

### ISSUE THREAD

**Issue by norpol** [metachris/metalab-git-workshop#35]
Do it! Now!

**Comment by keikoro** [comment]
Tut sich hier noch was?

**Comment by metachris** [comment]
Nope :)

**Comment by norpol** [comment]
Find ich schon.

**Comment by metachris** [comment]
cool :+1:

**Comment by metachris** [comment]
was machen wir?

**Comment by keikoro** [comment]
Meine Frage wär eigentlich gewesen, ob sich hinsichtlich des Workshops noch was tut... (;

**Comment by norpol** [comment]
Achso. Das nicht, Ticket bitte trotzdem offen lassen.

**Comment by metachris** [comment]
Wir könnten aber mal wieder nen workshop machen.

**Comment by keikoro** [comment]
Yes, please! Ich hab dir deswegen sogar mal gemailt, kam aber nix zurück. :3

**Comment by metachris** [comment]
Alright, dann machen wir das! :)

@kerstin ich hatte die letzten 6 Wochen so viel um die Ohren dass dein Mail untergegangen ist, sorry.

**Comment by metachris** [comment]
Insofern wäre vielleicht sowohl eine Einsteiger sowie eine Fortgeschrittenen Session am Besten... Oder meint ihr mal nur Fortgeschritten?

**Comment by keikoro** [comment]
Na welches Level wäre denn die Fortsetzung dessen, was bisher gemacht wurde? (; Was dazwischen?

**Comment by metachris** [comment]
Letztes Mal sind wir ganz mir Team-Workflows fertig geworden, da gibts eigentlich nix mehr dazu.

Vielleicht am Besten beide -- zuerst eine "Single User Git" Session, dann eine "Multi User Git" session.
